export const GET_MENU = "SET_HOME";
export const CHANGE_RIGHT = "CHANGE_RIGHT";
export const CHANGE_LEFT = "CHANGE_LEFT";
export const CHANGE_CENTER = "CHANGE_CENTER";
export const CHANGE_SHOW_MUSIC = "CHANGE_SHOW_MUSIC";
export const GET_USER_PLAYLISTS = "GET_USER_PLAYLISTS";
export const FIND_MAIN_PLAYLIST = "FIND_MAIN_PLAYLIST";
export const IS_ADDING_NEW_SONG_TO_PLAYLIST = "IS_ADDING_NEW_SONG_TO_PLAYLIST";
export const SET_SONG_ID = "SET_SONG_ID";
export const GET_CONFIGS = "GET_CONFIGS";
export const CHANGE_SHOW_CREATE_LIST = "CHANGE_SHOW_CREATE_LIST";
export const THIS_SONG_HAS_BEEN_ADD = "THIS_SONG_HAS_BEEN_ADD";
export const CHANGE_MY_PROFILE_MY_SONGLIST_ID =
  "CHANGE_MY_PROFILE_MY_SONGLIST_ID";
export const SET_LOADING_ON_USER_PLAYLIST = "SET_LOADING_ON_USER_PLAYLIST";
export const REMOVE_LOADING_ON_USER_PLAYLIST =
  "REMOVE_LOADING_ON_USER_PLAYLIST";
