export const LOGIN_SUCCESS = 'CHANGE_CENTER';
export const LOGIN_FAIL = 'CHANGE_CENTER';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';
